[package]
name = "concurrency"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "*", features = [
    "sqlite",
    "runtime-tokio-native-tls",
    "macros",
] }

tokio = { version = "*", features = ["full"] }
